services:
  - type: web
    name: opencap-visualizer
    env: static
    buildCommand: NODE_OPTIONS="--max-old-space-size=4096" npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 